---
# 2020/10/04
- name: 過去バージョンの削除
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: 前提パッケージのインストール
  apt:
    update_cache: yes
    state: present
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add apt repository
  apt_repository:
    repo: "deb [arch=arm64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: install docker engine
  apt:
    update_cache: yes
    state: present
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

# dockerユーザーの用意
